"""create release table

Revision ID: 0ec54e6bff41
Revises: 8b9f0f7c4a21
Create Date: 2026-06-05 00:04:51.594642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec54e6bff41'
down_revision: Union[str, Sequence[str], None] = '8b9f0f7c4a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('release_type', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('target_date', sa.String(length=40), nullable=False),
    sa.Column('shipped_at', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=False),
    sa.Column('public_notes', sa.Text(), nullable=False),
    sa.Column('included_feature_ids', sa.JSON(), nullable=False),
    sa.Column('included_bug_ids', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('releases')
    # ### end Alembic commands ###
