"""create feeback table

Revision ID: 5666d56b8e68
Revises: 
Create Date: 2026-05-20 12:35:19.849854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5666d56b8e68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=False),
    sa.Column('request', sa.String(length=500), nullable=False),
    sa.Column('product_area', sa.String(length=80), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=40), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('linked_feature', sa.String(length=160), nullable=False),
    sa.Column('received_at', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
