"""create roadmap features table

Revision ID: 721988a59a27
Revises: 00ca7f3e6d22
Create Date: 2026-06-01 14:52:46.902796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721988a59a27'
down_revision: Union[str, Sequence[str], None] = '00ca7f3e6d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_features', sa.Column('milestone', sa.String(length=120), nullable=True))
    op.drop_column('roadmap_features', 'milstone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_features', sa.Column('milstone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('roadmap_features', 'milestone')
    # ### end Alembic commands ###
